# Required metadata for SonarCloud
sonar.projectKey=YOUR_GENERATED_PROJECT_KEY
sonar.organization=devops1442

# The directory containing the code you want to scan
sonar.sources=.

# Exclude the GitHub Actions configuration from being analyzed
sonar.exclusions=.github/**
